language: python
python:
  - "3.6"
cache: pip

install:
  - pip install -r requirements.txt

script:
  - coverage run -m pytest
  - py.test --cov=project

after_success:
  - coveralls

script:
  - pytest
